src/portfolio/urls.py
from django.contrib import admin
from django.urls import path, include

from portfolio import views

urlpatterns = [
    path('', views.index, name='index'),
    path('about', views.about, name='about'),
    path('contact', views.contact, name='contact'),
    path('projects/', include('project.urls')),
    path('admin/', admin.site.urls),
]

src/project/urls.py
from django.urls import path
from project import views

app_name = 'project'

urlpatterns = [
    path('', views.projects, name='all'),
    path('project-details', views.details, name='details'),
]

src/project/models.py
from django.db import models

# Create your models here.

src/portfolio/views.py
from django.shortcuts import render

def index(req):
    template = 'index.html'
    data = {}
    data['page_title'] = 'eusuf ahamed - portfolio'
    
    return render(req, template, data)

def about(req):
    template = 'pages/about.html'
    data = {}
    data['page_title'] = 'about - eusuf ahamed'
    
    return render(req, template, data)

def contact(req):
    template = 'pages/contact.html'
    data = {}
    data['page_title'] = 'contact - eusuf ahamed'
    
    return render(req, template, data)

src/project/views.py
from django.shortcuts import render

def projects(req):
    template = 'pages/projects.html'
    data = {}
    data['page_title'] = 'projects - eusuf ahamed'

    return render(req, template, data)
def details(req):
    template = 'pages/project_details.html'
    data = {}
    data['page_title'] = 'daynamic'

    return render(req, template, data)

src/portfolio/templates/index.html
{% extends 'layouts/base.html' %}
{% load static %}

{% block title %}
{{ page_title | title }}
{% endblock %}

{% block content %}
<!-- Container -->
<main class="container">
    <div class="home-slider">
        <!-- Slider -->
        <div class="controls">
            <!-- Controls -->
            <div class="controls-navigate">
                <div class="prev">
                    <svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 456.5 980" style="enable-background:new 0 0 456.5 980;" xml:space="preserve">
                        <style type="text/css">
                            .st0 {
                            fill: #0FBFE6;
                            }
                        </style>
                        <path class="st0" d="M417,980c21.8,0,39.4-17.6,39.5-39.3c0-10.5-4.1-20.6-11.6-28L118.6,586.5c-53.2-53.2-53.2-139.7,0-192.8
                                    L444.9,67.4c15.2-15.6,14.9-40.6-0.7-55.8c-15.3-14.9-39.7-14.9-55.1,0L62.9,337.8c-83.9,83.9-83.9,220.4,0,304.3l326.3,326.4
                                    C396.6,975.9,406.6,980.1,417,980z"/>
                    </svg>
                </div>
            
                <div class="next">
                    <svg version="1.1" id="Layer_2" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 456.5 980" style="enable-background:new 0 0 456.5 980;" xml:space="preserve">
                        <style type="text/css">
                            .st0 {
                            fill: #0FBFE6;
                            }
                        </style>
                        <path class="st0" d="M39.5,0.1C17.7,0,0,17.6,0,39.4c0,10.5,4.1,20.6,11.6,28l326.3,326.3c53.2,53.2,53.2,139.7,0,192.8L11.6,912.7
                                    c-15.6,15.2-15.9,40.2-0.7,55.8s40.2,15.9,55.8,0.7c0.2-0.2,0.5-0.5,0.7-0.7l326.2-326.3c83.9-83.9,83.9-220.4,0-304.3L67.2,11.5
                                    C59.9,4.1,49.9,0,39.5,0.1z"/>
                    </svg>
                </div>
            </div>
            <!-- /Controls -->
        </div>
      
        <ul class="home-slider-horizontal">
            <li class="slide">
                <a href="gallery-images-col-3.html">
                    <div class="s-bg" style="background-image: url(/static/images/projects/1_fhifps.jpg)"></div>

                    <div class="slide-desc">
                        <h2>now or never</h2>
                    </div>
                </a>
            </li>
        </ul>
        <!-- /Slider -->
    </div>
</main>
<!-- /Container -->
{% endblock %}

src/portfolio/templates/layouts/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="keywords" content=""/>
    <meta name="description" content="Ronin HTML Template"/>

    <!-- Favicon -->
    <link rel="icon" type="image/png" href="assets/images/ico/favicon-16x16.png" sizes="16x16"/>

    <title>
        {% block title %}
        {% endblock %}
    </title>

    <!-- Bootstrap -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

    <!-- Plugins -->
    <link rel='stylesheet' href="{% static 'css/font-awesome.min.css' %}">
    <link rel='stylesheet' href="{% static 'css/lightgallery.min.css' %}">
    <link rel='stylesheet' href="{% static 'css/slick.css' %}">
    <link rel='stylesheet' href="{% static 'css/zoom.css' %}">

    <!-- Custom css file -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>

<body>
    <!-- Wrapper -->
    <div class="wrapper">
        {% include 'layouts/partials/_header.html' %}

        {% block content %}
        {% endblock %}

        {% include 'layouts/partials/_footer.html' %}
    </div>
    <!-- /Wrapper -->

    <!-- JS -->
    <!-- jquery-2.1.3.min js -->
    <script type="text/javascript" src="{% static 'js/jquery-2.1.3.min.js' %}"></script>

    <!-- Plugins -->
    <script type="text/javascript" src="{% static 'js/libs.js' %}"></script>

    <!-- Main js -->
    <script type="text/javascript" src="{% static 'js/main.js' %}"></script>
</body>
</html>

src/portfolio/templates/layouts/partials/_footer.html
{% load static %}
<!-- Footer -->
{% if page_title == 'eusuf ahamed - portfolio' %}
<footer id="footer" class="fix">
{% else %}
<footer id="footer">
{% endif %}
  <div class="row">
    <p class="col-xs-12 col-sm-6 col-md-6">Copyright © <script>document.write(new Date().getFullYear())</script> All Rights Reserved.</p>
    
    <ul class="follow col-xs-6 col-sm-6 col-md-6 hidden-xs">
      <li><p>Follow Us</p></li>
      <li><span></span></li>
      
      <li><a href="#"><i class="fa fa-facebook"></i></a></li>
      <li><a href="#"><i class="fa fa-twitter"></i></a></li>
      <li><a href="#"><i class="fa fa-dribbble"></i></a></li>
      <li><a href="#"><i class="fa fa-behance"></i></a></li>
      <li><a href="#"><i class="fa fa-rss"></i></a></li>
    </ul>
  </div>
</footer>
<!-- /Footer -->

src/portfolio/templates/layouts/partials/_header.html
{% load static %}
<!-- Header -->
<nav class="header row auto-hide-header page-transition">
  <div class="header-inner">
    <div class="logo col-xs-10 col-md-2">
      <a href="{% url 'index' %}"><img src="{% static 'images/ronin_logo.svg' %}" alt="logo"></a>
    </div>

    <div class="col-xs-2 col-md-10 visible-xs">
      <a href="#" class="nav-trigger"><span><em aria-hidden="true"></em>Menu</span></a>
    </div>

    <!-- Menu -->
    <div class="menu col-sm-8 col-md-10" id="menu">
      <ul>
        <li>
          <a href="{% url 'index' %}">home</a>
        </li>
        
        <li>
          <a href="{% url 'about' %}">about</a>
        </li>

        <li>
          <a href="{% url 'project:all' %}">projects</a>
        </li>

        <li>
          <a href="{% url 'contact' %}">contact</a>
        </li>
      </ul>
    </div>
    <!-- Menu -->
  </div>
</nav>
<!-- /Header -->

src/portfolio/templates/pages/about.html
{% extends 'layouts/base.html' %}
{% load static %}

{% block title %}
{{ page_title | title }}
{% endblock %}

{% block content %}
<!-- Container -->
<main class="container">
  <!-- Heading -->
  <div class="heading">
    <h2 class="head-text">
      <span>about me</span>
      <span>Simplicity, wit, and good typography.</span>
    </h2>
    <ul class="breadcrumb page-transition">
      <li>
        <a href="index.html">Home</a>
      </li>
      <li>
        <a href="about-us.html">about</a>
      </li>
      <li class="current-crumb">
        <a href="about-me.html">about me</a>
      </li>
    </ul>
  </div>
  <!-- /Heading -->
  <!-- About Me-->
  <div class="about-me">
    <div class="line"></div>
    <div class="row">
      <div class="content-box">
        <div class="team-photo col-md-4 col-sm-12">
          <img src="{% static 'images/team/team_1.jpg' %}" alt="image description">
        </div>
        <div class="team-info col-md-8 col-sm-12">
          <h2>Eusuf Ahamed</h2>
          <span>software engineer</span>
          <p>Enthusiastically redefine vertical users vis-a-vis highly efficient mindshare. Efficiently e-enable enabled e-commerce and market positioning potentialities. Seamlessly mesh empowered bandwidth whereas extensive relationships. Dynamically synergize wireless methodologies via worldwide resources. Progressively enhance visionary total linkage via end-to-end e-services. Interactively maximize inexpensive methodologies and interoperable technologies. Monotonectally aggregate extensive partnerships through equity invested catalysts for change. Synergistically fabricate extensible paradigms for high-quality paradigms. Conveniently foster B2B functionalities and innovative supply chains. Enthusiastically repurpose dynamic opportunities via stand-alone results.</p>
          <ul class="share">
            <li>
              <a href="#">
                <i class="fa fa-facebook" style="color: #3b5998;"></i>
              </a>
            </li>
            <li>
              <a href="#">
                <i class="fa fa-twitter" style="color: #55acee;"></i>
              </a>
            </li>
            <li>
              <a href="#">
                <i class="fa fa-dribbble" style="color: #ea4c89;"></i>
              </a>
            </li>
            <li>
              <a href="#">
                <i class="fa fa-behance" style="color: #1769FF;"></i>
              </a>
            </li>
            <li>
              <a href="#">
                <i class="fa fa-pinterest" style="color: #bd081c;"></i>
              </a>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <!-- /About Me-->

  <!-- About Us-->
  <div class="about">
    <div class="row">
        <!-- Team Info -->
        <div class="content-box">
            <div class="col-md-12">
                <article class="about-facts col-xs-12 col-md-6">
                    <h2>Some fact's about me</h2>
                    <p>Style never met and those among great. At no or september sportsmen he perfectly happiness attending. Depending listening delivered off new she procuring satisfied sex existence. Person plenty answer to exeter it if. Law use assistance especially resolution cultivated did out sentiments unsatiable. Way necessary had intention happiness but september delighted his curiosity. Furniture furnished or on strangers neglected remainder engrossed. </p>
                </article>
                <div class="about-skills col-xs-12 col-md-6">
                    <h2>Skills</h2>
                    <div class="skills">
                        <div class="skill">
                            <p class="skill-title">Web Development</p>
                            <div class="skill-bar" data-bar="90"><span></span></div>
                        </div>
                        <div class="skill">
                            <p class="skill-title">Consulting</p>
                            <div class="skill-bar" data-bar="70"><span></span></div>
                        </div>
                        <div class="skill">
                            <p class="skill-title">Branding</p>
                            <div class="skill-bar" data-bar="60"><span></span></div>
                        </div>
                        <div class="skill">
                            <p class="skill-title">Graphic Design</p>
                            <div class="skill-bar" data-bar="80"><span></span></div>
                        </div>
                    </div>
                </div>
            </div>  
        </div>
        <!-- /Team Info -->
        <!-- Services -->
            <div class="content-box">
                <article class="col-md-12">
                    <h2>what i offer</h2>
                    <p>He my polite be object oh change. Consider no mr am overcame yourself throwing sociable children. Hastily her totally conduct may. My solid by stuff first smile fanny. Humoured how advanced mrs elegance sir who. Home sons when them dine do want to. Estimating themselves unsatiable imprudence an he at an. Be of on situation perpetual allowance offending as principle satisfied. Improved carriage securing are desirous too.</p>
                </article>
                <div class="service-item col-md-4 col-xs-12 col-sm-6">
                    <h3><i class="fa fa-desktop"></i>Web Design</h3>
                    <p>Sportsman do allowance is september shameless am sincerity oh recommend. Gate tell man day that who.</p>
                </div>
                <div class="service-item col-md-4 col-xs-12 col-sm-6">
                    <h3><i class="fa fa-cogs"></i>Development</h3>
                    <p>Doubtful offended do entrance of landlord moreover is mistress in. Nay was appear entire ladies.</p>
                </div>
                <div class="service-item col-md-4 col-xs-12 col-sm-6">
                    <h3><i class="fa fa-pencil-square-o"></i>Graphic Design</h3>
                    <p>An seems green be wrote again. She add what own only like. Tolerably we as extremity exquisite do commanded.</p>
                </div>
                <div class="service-item col-md-4 col-xs-12 col-sm-6">
                    <h3><i class="fa fa-line-chart"></i>Marketing Strategy</h3>
                    <p>Wished be do mutual except in effect answer. Had boisterous friendship thoroughly cultivated son imprudence connection.</p>
                </div>
                <div class="service-item col-md-4 col-xs-12 col-sm-6">
                    <h3><i class="fa fa-list-alt"></i>Content Creation</h3>
                    <p>Debating me breeding be answered an he. Spoil event was words her off cause any. Tears woman which no is world miles woody.</p>
                </div>
                <div class="service-item col-md-4 col-xs-12 col-sm-6">
                    <h3><i class="fa fa-hand-pointer-o"></i>Interactive</h3>
                    <p>Carriage quitting securing be appetite it declared. High eyes kept so busy feel call in. Would day nor ask walls known.</p>
                </div>
            </div>
        <!-- /Services -->
        <!-- Clients -->
            <div class="content-box">
                <article class="col-xs-12 col-md-12">
                    <h2>Clients who love me</h2>
                    <p>To they four in love. Settling you has separate supplied bed. Concluded resembled suspected his resources curiosity joy. There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable.</p>
                </article>
                <ul class="clients col-xs-12 col-md-12">
                    <li class="client col-md-2 col-xs-4">
                    <span>
                        <img src="assets/images/clients/client-1.png" alt="image description">
                    </span>
                    </li>
                    <li class="client col-md-2 col-xs-4">
                    <span>
                        <img src="assets/images/clients/client-2.png" alt="image description">
                    </span>
                    </li>
                    <li class="client col-md-2 col-xs-4">
                    <span>
                        <img src="assets/images/clients/client-3.png" alt="image description">
                    </span>
                    </li>
                    <li class="client col-md-2 col-xs-4">
                    <span>
                        <img src="assets/images/clients/client-4.png" alt="image description">
                    </span>
                    </li>
                    <li class="client col-md-2 col-xs-4">
                    <span>
                        <img src="assets/images/clients/client-5.png" alt="image description">
                    </span>
                    </li>
                    <li class="client col-md-2 col-xs-4">
                    <span>
                        <img src="assets/images/clients/client-6.png" alt="image description">
                    </span>
                    </li>
                </ul>
            </div>
        <!-- Clients -->
    </div>
</div>
<!-- /About Us-->
</main>
<!-- /Container -->
{% endblock %}

src/portfolio/templates/pages/contact.html
{% extends 'layouts/base.html' %}
{% load static %}

{% block title %}
{{ page_title | title }}
{% endblock %}

{% block content %}
<!-- Container -->
<main class="container">
    <!-- Header -->
    <div class="heading">
      <h2 class="head-text">
        <span>Contact</span>
        <span>The soul never thinks without an image.</span>
      </h2>
      <ul class="breadcrumb page-transition">
        <li>
          <a href="index.html">home</a>
        </li>
        <li class="current-crumb">
          <a href="#">Contact</a>
        </li>
      </ul>
    </div>
    <!-- /Header -->
    <!-- Contact -->
    <div class="contact">
      <div class="line"></div>
      <div class="row">
        <div class="content-box">
          <div class="contact-info col-sm-12 col-md-6">
            <h2>info contact</h2>
            <p>Duis ut ullamcorper ipsum. Etiam porttitor.</p>
            <div class="contact-details">
              <div class="col-md-12">
                <i class="fa fa-map-marker" aria-hidden="true"></i> 57 Mainstreet, MainTower, Barcelona
              </div>
              <div class="col-md-12">
                <i class="fa fa-volume-control-phone" aria-hidden="true"></i> +99(004) 987-654-3210
              </div>
              <div class="col-md-12">
                <i class="fa fa-envelope" aria-hidden="true"></i> contact@ronin.com
              </div>
            </div>
          </div>
          <div class="contact-form col-sm-12 col-md-6">
            <h2>keep in touch</h2>
            <p>Nunc nec iaculis ipsum, a egestas ante.</p>
            <form id="validForm">
              <div class="form-group control-group col-sm-12 col-md-6">
                <span>
                  <i class="fa fa-user"></i>
                </span>
                <input class="form-control" type="text" name="name" minlength="2" placeholder="Name *" autocomplete="off">
              </div>
              <div class="form-group control-group col-sm-12 col-md-6">
                <span>
                  <i class="fa fa-envelope-o"></i>
                </span>
                <input class="form-control" type="email" name="email" placeholder="Email Address *" autocomplete="off">
              </div>
              <div class="form-group control-group col-sm-12">
                <span>
                  <i class="fa fa-pencil"></i>
                </span>
                <textarea class="form-control" name="message" placeholder="Message *"></textarea>
              </div>
              <div class="form-button col-xs-12">
                <button type="submit" name="enter" class="button">
                  <i class="fa fa-paper-plane"></i>
                  <span>send message</span>
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
    <!-- /Contact -->
</main>
<!-- /Container -->
{% endblock %}

src/project/templates/pages/projects.html
{% extends 'layouts/base.html' %}
{% load static %}

{% block title %}
{{ page_title | title }}
{% endblock %}

{% block content %}
<!-- Container -->
<main class="container">
    <!-- Header -->
    <div class="heading">
      <h2 class="head-text">
        <span>work's</span>
        <span>Design is a solution to a problem.</span>
      </h2>
      <ul class="breadcrumb page-transition">
        <li>
          <a href="index.html">Home</a>
        </li>
        <li class="current-crumb">
          <a href="#">works col. 2</a>
        </li>
      </ul>
    </div>
    <!-- /Header -->
    <!--Works-->
    <div class="works">
      <div class="line"></div>
      <div class="works-content page-transition">
        <div id="filters">
          <button class="btn-filter current" data-filter="*">show all</button>
          <button class="btn-filter" data-filter=".design">design</button>
          <button class="btn-filter" data-filter=".branding">branding</button>
          <button class="btn-filter" data-filter=".art">art</button>
        </div>
        <ul class="grid">
          <li class="grid-item col-md-6 col-sm-6 col-xs-12 branding">
            <a href="{% url 'project:details' %}">
              <img src="{% static 'images/works/thumb/w-1.jpg' %}" alt="img-desc">
              <div class="grid-overlay">
                <div class="work-text">
                  <span class="work-cat">branding</span>
                  <div class="work-name">
                    <h3>The Grey Magic</h3>
                    <span class="triangle">
                      <i class="fa fa-angle-right fa-2x" aria-hidden="true"></i>
                    </span>
                  </div>
                </div>
              </div>
            </a>
          </li>
          <li class="grid-item col-md-6 col-sm-6 col-xs-12 design">
            <a href="project-video.html">
              <img src="{% static 'images/works/thumb/w-2.jpg' %}" alt="img-desc">
              <div class="grid-overlay">
                <div class="work-text">
                  <span class="work-cat">design</span>
                  <div class="work-name">
                    <h3>Eyes of Stones</h3>
                    <span class="triangle">
                      <i class="fa fa-angle-right fa-2x" aria-hidden="true"></i>
                    </span>
                  </div>
                </div>
              </div>
            </a>
          </li>
          <li class="grid-item col-md-6 col-sm-6 col-xs-12 art">
            <a href="project-video.html">
              <img src="{% static 'images/works/thumb/w-3.jpg' %}" alt="img-desc">
              <div class="grid-overlay">
                <div class="work-text">
                  <span class="work-cat">art</span>
                  <div class="work-name">
                    <h3>Spirit in the Secret</h3 <span class="triangle">
                    <i class="fa fa-angle-right fa-2x" aria-hidden="true"></i>
                    </span>
                  </div>
                </div>
              </div>
            </a>
          </li>
          <li class="grid-item col-md-6 col-sm-6 col-xs-12 branding">
            <a href="project-video.html">
              <img src="{% static 'images/works/thumb/w-4.jpg' %}" alt="img-desc">
              <div class="grid-overlay">
                <div class="work-text">
                  <span class="work-cat">branding</span>
                  <div class="work-name">
                    <h3>No Time</h3>
                    <span class="triangle">
                      <i class="fa fa-angle-right fa-2x" aria-hidden="true"></i>
                    </span>
                  </div>
                </div>
              </div>
            </a>
          </li>
          <li class="grid-item col-md-6 col-sm-6 col-xs-12 design">
            <a href="project-video.html">
              <img src="{% static 'images/works/thumb/w-5.jpg' %}" alt="img-desc">
              <div class="grid-overlay">
                <div class="work-text">
                  <span class="work-cat">design</span>
                  <div class="work-name">
                    <h3>Moons of Window</h3>
                    <span class="triangle">
                      <i class="fa fa-angle-right fa-2x" aria-hidden="true"></i>
                    </span>
                  </div>
                </div>
              </div>
            </a>
          </li>
          <li class="grid-item col-md-6 col-sm-6 col-xs-12 art">
            <a href="project-video.html">
              <img src="{% static 'images/works/thumb/w-6.jpg' %}" alt="img-desc">
              <div class="grid-overlay">
                <div class="work-text">
                  <span class="work-cat">art</span>
                  <div class="work-name">
                    <h3>The Rings's Shores</h3>
                    <span class="triangle">
                      <i class="fa fa-angle-right fa-2x" aria-hidden="true"></i>
                    </span>
                  </div>
                </div>
              </div>
            </a>
          </li>
        </ul>
        <div class="more">
          <a href="#" class="button">
            <i class="fa fa-plus"></i>
            <span>Load More</span>
          </a>
        </div>
      </div>
    </div>
    <!--/Works-->
</main>
<!-- /Container -->
{% endblock %}